version: '3.3'

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
      image: timik2t/foodgram_backend:latest
      restart: always
      volumes:
          - static_value:/app/static/
          - media_value:/app/media/
      depends_on:
          - db
      env_file:
          - ./.env

  frontend:
    image: timik2t/foodgram_frontend:v1.0
    restart: always
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
          - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/code/dj_static/
      - media_value:/code/dj_media/
      - ../frontend/build:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/

    restart: always
    
    depends_on:
            - backend
            - frontend
    
volumes:
  postgres_data:
  static_value:
  media_value:
