# Generated by Django 4.1.1 on 2022-09-17 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0002_shoppingcart_favorite_favorite_favorite_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'verbose_name': 'Количество ингредиента для рецепта'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#49B64E', help_text='https://colorscheme.ru/html-colors.html', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Введите валидный цветовой HEX-код!', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Цветовой HEX-код'),
        ),
    ]
