# Generated by Django 4.1.1 on 2022-09-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_time_in_minutes',
            new_name='cooking_time',
        ),
    ]
