# Generated by Django 3.2.6 on 2022-10-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=5, verbose_name='Роль'),
        ),
    ]
