# Generated by Django 4.1.1 on 2022-10-09 14:14

from django.db import migrations, models
import users.validations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[users.validations.validate_username], verbose_name='Логин'),
        ),
    ]
