# Generated by Django 3.2.6 on 2022-10-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=5, verbose_name='Роль'),
        ),
    ]
